use std::str::FromStr;

#[derive(PartialEq, Debug)]
pub enum Reaction {
    AirKiss,
    AngryStare,
    Bite,
    Bleh,
    Blush,
    Brofist,
    Celebrate,
    Cheers,
    Clap,
    Confused,
    Cool,
    Cry,
    Cuddle,
    Dance,
    Drool,
    EvilLaugh,
    Facepalm,
    Handhold,
    Happy,
    HeadBang,
    Hug,
    Kiss,
    Laugh,
    Lick,
    Love,
    Mad,
    Nervous,
    No,
    Nom,
    Nosebleed,
    Nuzzle,
    Nyah,
    Pat,
    Peek,
    Pinch,
    Poke,
    Pout,
    Punch,
    Roll,
    Run,
    Sad,
    Scared,
    Shrug,
    Shy,
    Sigh,
    Sip,
    Slap,
    Sleep,
    SlowClap,
    Smack,
    Smile,
    Smug,
    Sneeze,
    Sorry,
    Stare,
    Stop,
    Surprised,
    Sweat,
    ThumbsUp,
    Tickle,
    Tired,
    Wave,
    Wink,
    Woah,
    Yawn,
    Yay,
    Yes,
}

impl FromStr for Reaction {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "airkiss" => Ok(Reaction::AirKiss),
            "angrystare" => Ok(Reaction::AngryStare),
            "bite" => Ok(Reaction::Bite),
            "bleh" => Ok(Reaction::Bleh),
            "blush" => Ok(Reaction::Blush),
            "brofist" => Ok(Reaction::Brofist),
            "celebrate" => Ok(Reaction::Celebrate),
            "cheers" => Ok(Reaction::Cheers),
            "clap" => Ok(Reaction::Clap),
            "confused" => Ok(Reaction::Confused),
            "cool" => Ok(Reaction::Cool),
            "cry" => Ok(Reaction::Cry),
            "cuddle" => Ok(Reaction::Cuddle),
            "dance" => Ok(Reaction::Dance),
            "drool" => Ok(Reaction::Drool),
            "evillaugh" => Ok(Reaction::EvilLaugh),
            "facepalm" => Ok(Reaction::Facepalm),
            "handhold" => Ok(Reaction::Handhold),
            "happy" => Ok(Reaction::Happy),
            "headbang" => Ok(Reaction::HeadBang),
            "hug" => Ok(Reaction::Hug),
            "kiss" => Ok(Reaction::Kiss),
            "laugh" => Ok(Reaction::Laugh),
            "lick" => Ok(Reaction::Lick),
            "love" => Ok(Reaction::Love),
            "mad" => Ok(Reaction::Mad),
            "nervous" => Ok(Reaction::Nervous),
            "no" => Ok(Reaction::No),
            "nom" => Ok(Reaction::Nom),
            "nosebleed" => Ok(Reaction::Nosebleed),
            "nuzzle" => Ok(Reaction::Nuzzle),
            "nyah" => Ok(Reaction::Nyah),
            "pat" => Ok(Reaction::Pat),
            "peek" => Ok(Reaction::Peek),
            "pinch" => Ok(Reaction::Pinch),
            "poke" => Ok(Reaction::Poke),
            "pout" => Ok(Reaction::Pout),
            "punch" => Ok(Reaction::Punch),
            "roll" => Ok(Reaction::Roll),
            "run" => Ok(Reaction::Run),
            "sad" => Ok(Reaction::Sad),
            "scared" => Ok(Reaction::Scared),
            "shrug" => Ok(Reaction::Shrug),
            "shy" => Ok(Reaction::Shy),
            "sigh" => Ok(Reaction::Sigh),
            "sip" => Ok(Reaction::Sip),
            "slap" => Ok(Reaction::Slap),
            "sleep" => Ok(Reaction::Sleep),
            "slowclap" => Ok(Reaction::SlowClap),
            "smack" => Ok(Reaction::Smack),
            "smile" => Ok(Reaction::Smile),
            "smug" => Ok(Reaction::Smug),
            "sneeze" => Ok(Reaction::Sneeze),
            "sorry" => Ok(Reaction::Sorry),
            "stare" => Ok(Reaction::Stare),
            "stop" => Ok(Reaction::Stop),
            "surprised" => Ok(Reaction::Surprised),
            "sweat" => Ok(Reaction::Sweat),
            "thumbsup" => Ok(Reaction::ThumbsUp),
            "tickle" => Ok(Reaction::Tickle),
            "tired" => Ok(Reaction::Tired),
            "wave" => Ok(Reaction::Wave),
            "wink" => Ok(Reaction::Wink),
            "woah" => Ok(Reaction::Woah),
            "yawn" => Ok(Reaction::Yawn),
            "yay" => Ok(Reaction::Yay),
            "yes" => Ok(Reaction::Yes),
            _ => Err(()),
        }
    }
}

impl Reaction {
    pub(crate) fn as_str(&self) -> &str {
        match *self {
            Reaction::AirKiss => "airkiss",
            Reaction::AngryStare => "angrystare",
            Reaction::Bite => "bite",
            Reaction::Bleh => "bleh",
            Reaction::Blush => "blush",
            Reaction::Brofist => "brofist",
            Reaction::Celebrate => "celebrate",
            Reaction::Cheers => "cheers",
            Reaction::Clap => "clap",
            Reaction::Confused => "confused",
            Reaction::Cool => "cool",
            Reaction::Cry => "cry",
            Reaction::Cuddle => "cuddle",
            Reaction::Dance => "dance",
            Reaction::Drool => "drool",
            Reaction::EvilLaugh => "evillaugh",
            Reaction::Facepalm => "facepalm",
            Reaction::Handhold => "handhold",
            Reaction::Happy => "happy",
            Reaction::HeadBang => "headbang",
            Reaction::Hug => "hug",
            Reaction::Kiss => "kiss",
            Reaction::Laugh => "laugh",
            Reaction::Lick => "lick",
            Reaction::Love => "love",
            Reaction::Mad => "mad",
            Reaction::Nervous => "nervous",
            Reaction::No => "no",
            Reaction::Nom => "nom",
            Reaction::Nosebleed => "nosebleed",
            Reaction::Nuzzle => "nuzzle",
            Reaction::Nyah => "nyah",
            Reaction::Pat => "pat",
            Reaction::Peek => "peek",
            Reaction::Pinch => "pinch",
            Reaction::Poke => "poke",
            Reaction::Pout => "pout",
            Reaction::Punch => "punch",
            Reaction::Roll => "roll",
            Reaction::Run => "run",
            Reaction::Sad => "sad",
            Reaction::Scared => "scared",
            Reaction::Shrug => "shrug",
            Reaction::Shy => "shy",
            Reaction::Sigh => "sigh",
            Reaction::Sip => "sip",
            Reaction::Slap => "slap",
            Reaction::Sleep => "sleep",
            Reaction::SlowClap => "slowclap",
            Reaction::Smack => "smack",
            Reaction::Smile => "smile",
            Reaction::Smug => "smug",
            Reaction::Sneeze => "sneeze",
            Reaction::Sorry => "sorry",
            Reaction::Stare => "stare",
            Reaction::Stop => "stop",
            Reaction::Surprised => "surprised",
            Reaction::Sweat => "sweat",
            Reaction::ThumbsUp => "thumbsup",
            Reaction::Tickle => "tickle",
            Reaction::Tired => "tired",
            Reaction::Wave => "wave",
            Reaction::Wink => "wink",
            Reaction::Woah => "woah",
            Reaction::Yawn => "yawn",
            Reaction::Yay => "yay",
            Reaction::Yes => "yes",
        }
    }
}